version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./OJT2026
    container_name: backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sampledb
      SPRING_DATASOURCE_USERNAME: sample
      SPRING_DATASOURCE_PASSWORD: sample
    ports:
      - "8080:8081"

  frontend:
    build: ./ojt_front
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
